[env]
TESTS_DIR = "${CARGO_MAKE_WORKING_DIRECTORY}/riscv-tests/isa/"

[tasks.pretest]
script = [
    "git submodule update --init --recursive riscv-tests",
    "cd ${TESTS_DIR}",
    "make -j8",
    "find . -maxdepth 1 -not -type d -name 'rv*' -printf '%f\n' | egrep -v '\\.dump$|\\.hex$|\\.bin$' | xargs -I {} riscv64-unknown-elf-objcopy -O binary {} {}.bin",
]

[tasks.run]
command = "cargo"
args = ["run", "-q", "--manifest-path", "cli/Cargo.toml", "${@}"]
